# ===== Profil DEV =====
# Logs SQL verbeux (utiles uniquement en développement)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Logs applicatifs
logging.level.tn.esprit.autoloc=DEBUG